// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ0W_qxGRViIP_qGYNG6r5mpWGRgLXpwI',
    appId: '1:973470529047:web:11c8d343d4ca7815cbce52',
    messagingSenderId: '973470529047',
    projectId: 'titik-kumpul-6b913',
    authDomain: 'titik-kumpul-6b913.firebaseapp.com',
    storageBucket: 'titik-kumpul-6b913.firebasestorage.app',
    measurementId: 'G-W13BLDPD9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy7O8XD0whXO0pTcS4aZy9BhkgfLwiaDw',
    appId: '1:973470529047:android:6fe02f7436ba81cecbce52',
    messagingSenderId: '973470529047',
    projectId: 'titik-kumpul-6b913',
    storageBucket: 'titik-kumpul-6b913.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtrxL3Y6QuyBynkziH7VbY7tpkQWkVoZ4',
    appId: '1:973470529047:ios:194586cb1f83908ccbce52',
    messagingSenderId: '973470529047',
    projectId: 'titik-kumpul-6b913',
    storageBucket: 'titik-kumpul-6b913.firebasestorage.app',
    iosBundleId: 'com.example.campusFoodRecommender',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtrxL3Y6QuyBynkziH7VbY7tpkQWkVoZ4',
    appId: '1:973470529047:ios:194586cb1f83908ccbce52',
    messagingSenderId: '973470529047',
    projectId: 'titik-kumpul-6b913',
    storageBucket: 'titik-kumpul-6b913.firebasestorage.app',
    iosBundleId: 'com.example.campusFoodRecommender',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ0W_qxGRViIP_qGYNG6r5mpWGRgLXpwI',
    appId: '1:973470529047:web:2f848eca56362387cbce52',
    messagingSenderId: '973470529047',
    projectId: 'titik-kumpul-6b913',
    authDomain: 'titik-kumpul-6b913.firebaseapp.com',
    storageBucket: 'titik-kumpul-6b913.firebasestorage.app',
    measurementId: 'G-6F2JFF1WM2',
  );
}
